import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "ARTventure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background-50"
      >
        {children}
      </body>
    </html>
  );
}
